---
site_name: terraform-azurerm-storage-account-website

repo_name: padok-team/terraform-azurerm-storage-account-website
repo_url: https://github.com/padok-team/terraform-azurerm-storage-account-website

plugins:
  - techdocs-core
